### PR TITLE
Create Calendar

### LINKED ISSUE #37: calendar.jsx
Screenshot 2024-07-14 at 7 51 10 PM

### PR DESCRIPTION
**Pull request by sunbrandon**
Screenshot 2024-07-27 at 10 54 56 AM
Unable to get it exactly like screenshot provided

### CODE REVIEW

**Review by stormyy00 — COMMENTED** [review]
look at the art factory css file since the rest you can't really do in tailwind
https://github.com/acm-ucr/art-factory-website/blob/dev/src/components/calendar/index.css

**Review by Howard-Z — APPROVED** [review]
can you update the ss

**Comment by sunbrandon** [comment]
don't merge, almost finish but not fully styled yet

**Comment by stormyy00** [comment]
> don't merge, almost finish but not fully styled yet

allg

**Pull request merged**
